name: CI Pipeline
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # Step 1: Checks out your repository's code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: A simple build step that just lists the files
    - name: List files in repository
      run: ls -l
